trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'
  persistCredentials: true


variables:
  imageRepository: 'joaovitor0305/tilabs'
  tag: '$(Build.BuildId)'
  persistCredentials: true


steps:
- task: Docker@2
  displayName: 'Login to Docker Hub'
  inputs:
    command: login
    containerRegistry: 'DockerHub'  # Assegure-se de configurar esta conexão de serviço no Azure DevOps

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Certifique-se que o caminho para o Dockerfile está correto
    containerRegistry: 'DockerHub'  # Nome da conexão de serviço configurada para Docker Hub
    tags: |
      $(tag)




